# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
defaults: &defaults
  working_directory: ~/repo

  docker:
      - image: circleci/node:8.6

version: 2
jobs:
  build:
    <<: *defaults

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: yarn test

      - run: yarn lint

      - run: yarn build

      - persist_to_workspace:
          root: ~/
          paths:
            - repo/dist
            - .ssh

  deploy:
    <<: *defaults

    steps:
      - attach_workspace:
          at: ~/

      - run:
          name: clone-mrbabbs.com
          command: |
            cd ..

            echo "Cloning mrbabbs.com repo ------>"
            git clone git@github.com:mrbabbs/mrbabbs.com.git
            echo "Done cloning mrbabbs.com repo <------"

            cd mrbabbs.com
            git checkout master

            echo "Installing dependecies ------>"
            npm install
            echo "Done installing dependecies <------"

      - run:
          name: deploy
          command: |
            echo "Set github user repo ------>"
            git config --global user.email circleci@circleci
            git config --global user.name CircleCIcd
            echo "Done set github user repo <------"

            echo "Copying app dist into mrbabbs.com ------>"
            rm -rf ~/mrbabbs.com/github-users-search-react
            cp -r ~/repo/dist ~/mrbabbs.com/github-users-search-react
            echo "Done copying add dist <------"

            echo "Add commit ------>"
            cd ~/mrbabbs.com/
            git add .
            git commit -m 'Add new build version of github-users-search-react'
            echo "Done add commit <------"

            echo "Bump version ------>"
            npm version minor -f
            echo "Done bump version <------"

            echo "Push on mrbabbs.com master ------>"
            git push origin master
            echo "Done push on mrbabbs.com master <------"


workflows:
  version: 2

  btd:
    jobs:
      - build
      - deploy:
          requires:
            - build

          filters:
            branches:
              only: master


